sudo: required

env:
  - APP_NAME=protected-dawn-39658

services: 
  - docker

before-install:
  - docker-compose up --build

script:
  - heroku stack:set --app $APP_NAME heroku-18
  - heroku config:get CLIENT_ID -a $APP_NAME -s  >> ./api/.env
  - heroku config:get CLIENT_SECRET -a $APP_NAME -s  >> ./api/.env
  - heroku config:get MLAB_CONN -a $APP_NAME -s  >> ./api/.env
  - heroku config:get PORT -a $APP_NAME -s  >> ./api/.env
  - docker-compose run api npm run test:coverage

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $APP_NAME
  on:
    branch: master

after_deploy:
  - docker-compose down
  - docker system prune -f
  - docker volume prune -f